#!/bin/bash

set -euo pipefail

# lookup git base folder
path::git-base() {
  local base
  # get super working dir if it's submodule
  base="$(git rev-parse --show-superproject-working-tree)"
  # otherwise get default working dir
  base="${base:-"$(git rev-parse --show-toplevel)"}"

  echo "${base}"
}

# set envs
: "${CLOUD_PATH_BASE:="$(path::git-base)/cloud-init"}"
: "${CLOUD_PATH_WRITE_FILES:="${CLOUD_PATH_BASE}/write_files"}"
: "${CLOUD_USER:="user"}"
: "${CLOUD_GROUP:="root"}"
: "${CLOUD_SSH_PUB:="${HOME}/.ssh/id_rsa.pub"}"

# readout local pub key
ssh::pub() {
  # read out pub key without hostname
  cut -d' ' -f-2 "${CLOUD_SSH_PUB}"
}

# generates all files base64 encoded
cloud::write_files() {
  local -r path_files="${CLOUD_PATH_WRITE_FILES}"

  # go thorugh ./write_files folder
  for file in $(find "${path_files}" -type f -not -name '*.stat'); do
    local stat="${file}.stat"
    local content=""
    local path="${file:${#path_files}}"
    local owner="${CLOUD_USER}:${CLOUD_GROUP}"
    local permissions='0655'

    [ ! -f "${stat}" ] || {
      ! grep -Eq '^owner: .+$' "${stat}" ||
        owner="$(sed -En 's/^owner: (.+)$/\1/p' "${stat}")"
      ! grep -Eq '^permissions: .+$' "${stat}" ||
        permissions="$(sed -En 's/^permissions: (.+)$/\1/p' "${stat}")"
      ! grep -q '^execute: true$' "${stat}" ||
        content="$(bash "${file}")"
    }

    cat <<EOF
- encoding: b64
  content: $(echo "${content:-"$(cat "${file}")"}" | base64 -w0)
  path: "${path}"
  owner: ${owner}
  permissions: '${permissions}'
EOF
  done
}

# generate runcmd commands
cloud::runcmd() {
  local -r path_files="${CLOUD_PATH_WRITE_FILES}"

  # go through *.stat files
  find "${path_files}" -type f -name '*.stat' -exec bash -c '
    ! grep -q "^runcmd: true$" "${1}" ||
      echo "- ${1:'${#path_files}':-5}"
  ' _ {} \;
}

# generate packages list
cloud::packages() {
  sed -e 's/^/- /g' "${CLOUD_PATH_BASE}/packages"
}

# generates nameserver list
cloud::nameservers() {
  sed -e 's/^/    - /g' "${CLOUD_PATH_BASE}/nameservers"
}

# print cloud-config
cloud::generate() {
  cat <<EOF
#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

disable_root: 1
ssh_pwauth:   0

manage-resolv-conf: true
resolv_conf:
  nameservers:
$(cloud::nameservers)

write_files:
$(cloud::write_files)

users:
- name: "${CLOUD_USER}"
  lock_passwd: true
  shell: /bin/bash
  ssh-authorized-keys:
    - "$(ssh::pub)"
  groups:
    - docker
  sudo:
    - ALL=(ALL) NOPASSWD:ALL

packages:
$(cloud::packages)

runcmd:
$(cloud::runcmd)

final_message: "The system is finally up, after \$UPTIME seconds"
EOF
}

# will be executed if script is called directly
main() {
  [ -d "${CLOUD_PATH_BASE}" ] || {
    echo "🐮 cloud-init path does not exists: ${CLOUD_PATH_BASE}"
    return 1
  }

  cloud::generate
}

# only execute if called directly
[[ "${0}" != "${BASH_SOURCE[0]}" ]] || main "${@}"
